# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nereare
email: igorpadoim@gmail.com
description: >
  This is the base site for Igor Padoim (a.k.a. Nereare), hosted with :heart: in
  GitHub.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nereare.github.io/"
twitter_username: nereare
github_username:  Nereare

excerpt_separator: <!--more-->
disqus:
  shortname: nereare
google_analytics: UA-84004924-2

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
